function Ad = Ad(in1,in2)
%Ad
%    Ad = Ad(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    13-May-2023 19:54:24

F_x = in2(1,:);
d_delta = in2(2,:);
psi = in1(3,:);
vx = in1(4,:);
vy = in1(5,:);
t2 = cos(psi);
t3 = sin(psi);
t4 = t2./2.0e+1;
t5 = t3./2.0e+1;
Ad = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,t3.*vx.*(-1.0./2.0e+1)-(t2.*vy)./2.0e+1,t4.*vx-(t3.*vy)./2.0e+1,1.0,0.0,0.0,0.0,0.0,t4,t5,0.0,1.0,d_delta./4.4e+1,d_delta.*(5.0./2.97e+2),0.0,-t5,t4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0./2.0e+1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,F_x./6.6e+4,F_x./8.91e+4,1.0],[7,7]);
