function f_c = f_c(in1,in2)
%F_C
%    F_C = F_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    13-May-2023 19:54:22

F_x = in2(1,:);
d_delta = in2(2,:);
delta = in1(7,:);
psi = in1(3,:);
r = in1(6,:);
vx = in1(4,:);
vy = in1(5,:);
t2 = cos(psi);
t3 = sin(psi);
f_c = [t2.*vx-t3.*vy;t3.*vx+t2.*vy;r;F_x./1.5e+3;(F_x.*delta)./3.3e+3+d_delta.*vx.*(5.0./1.1e+1);(F_x.*delta)./4.455e+3+d_delta.*vx.*(1.0e+2./2.97e+2);d_delta];
