function f_d = f_d(in1,in2)
%F_D
%    F_D = F_D(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    12-May-2023 11:55:43

F_x = in2(1,:);
X = in1(1,:);
Y = in1(2,:);
d_delta = in2(2,:);
delta = in1(7,:);
psi = in1(3,:);
r = in1(6,:);
vx = in1(4,:);
vy = in1(5,:);
t2 = cos(psi);
t3 = sin(psi);
f_d = [X+(t2.*vx)./2.0e+1-(t3.*vy)./2.0e+1;Y+(t3.*vx)./2.0e+1+(t2.*vy)./2.0e+1;psi+r./2.0e+1;F_x./3.0e+4+vx;vy+(F_x.*delta)./6.6e+4+(d_delta.*vx)./4.4e+1;r+(F_x.*delta)./8.91e+4+d_delta.*vx.*(5.0./2.97e+2);d_delta./2.0e+1+delta];
