function x = x(X,Y,psi,vx,vy,r,delta)
%X
%    x = X(X,Y,PSI,VX,VY,R,DELTA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    12-May-2023 11:55:42

x = [X;Y;psi;vx;vy;r;delta];
